import { AuthProvider } from './Providers'
import './globals.css'
import { Cairo } from 'next/font/google'

const inter = Cairo({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="ar" dir='rtl'>
            <body className={inter.className}>
                <AuthProvider>
                    {children}
                </AuthProvider>
            </body>
        </html>
    )
}
